Refactor project directory structure
cassini-Inner/inner-souce-management pull request #16
Opened 2020-03-18 10:35 UTC by Vulfpeck

Fixes #10

2020-03-18 11:20 UTC, AJaxRUN approved these changes

2020-03-18 11:23 UTC, merged

2020-03-19 05:56 UTC, sanghaiadarsh requested changes
Left some minor comments

2020-03-19 05:56 UTC, sanghaiadarsh commented on src/Components/Common/AuthorInfo/AuthorInfo.js
> +                {/* <p className="leading-tight text-s ">created on 17/01/2020</p> */}
do we need the commented bit here for future use?

2020-03-19 05:56 UTC, sanghaiadarsh commented on src/Components/Common/Dropdown/Dropdown.js
> +    let dropdownList = props.list.map((label) => {
use const

2020-03-19 05:56 UTC, sanghaiadarsh commented on src/Components/Common/SearchBar/SearchBar.js
> +    let inputClasses = "h-12 focus:outline-none rounded py-2 block w-full appearance-none leading-normal ";
use const

2020-03-19 05:56 UTC, sanghaiadarsh commented on src/Components/Containers/Modal.js
> +    let name = "overflow-y-hidden";
use const

2020-03-19 05:56 UTC, sanghaiadarsh commented on src/Components/Containers/Modal.js
> +    let name = "overflow-y-hidden";
use const

2020-03-19 05:56 UTC, sanghaiadarsh commented on src/Components/Jobs/JobList.js
> +                <SearchBar className="mt-2 mb-40 bg-nebula-grey-200 " inputClass="placeholder-nebula-grey-600 bg-nebula-grey-200" placeholder="Search for tags to add" /> */}
do we need the comments for future use?

2020-03-19 05:56 UTC, sanghaiadarsh commented on src/Components/routes/CreateJob/CreateJob.js
> +            </div>*/}
remove the comments if they are not needed please.

2020-03-19 06:16 UTC, Vulfpeck commented
Will make the changes